baseURL = "https://heng-mei.github.io/"
title = "Heng-Mei Blog"
theme = "FixIt"
locale = "zh-cn"
defaultContentLanguage = "zh"
enableRobotsTXT = true
enableEmoji = true

mainSections = ["dialogues", "posts", "algorithms", "notes"]

[outputs]
home = ["html", "rss", "archives", "offline", "readme", "baidu_urls", "search"]
page = ["html", "markdown"]
section = ["html", "rss"]
taxonomy = ["html"]
term = ["html", "rss"]

[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
collection = "collections"

[params]
version = "1.0.X"
capitalize_titles = false
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
page_style = "normal"
word_count = true
reading_time = true
collection_list = true

[params.breadcrumb]
enable = true

[params.podcast]
enable = false

[params.cookieconsent]
enable = false

[params.back_to_top]
enable = true
scrollpercent = true

[params.home]
[params.home.profile]
enable = true
gravatar_email = "l888999666y@gmail.com"
avatar_url = "/avatar.jpg"
avatar_menu = "github"
title = """Heng-Mei <img src="/face-in-clouds-emoji.gif" class="emoji"/>"""

subtitle = "横眉冷对千夫指，俯首甘为孺子牛。"
typeit = true
social = true

[params.home.posts]
enable = false

[params.author]
name = "Heng-Mei"
email = "l888999666y@gmail.com"
link = "https://github.com/Heng-Mei"
avatar = "/avatar.jpg"

[params.footer]
enable = true
copyright = true
author = true
since = "2025"
gov = ""
icp = ""
license = "<a href='https://opensource.org/licenses/MIT'>MIT License</a>"
[params.footer.powered]
enable = false

[params.search]
enable = true
type = "fuse"
content_length = 4000
placeholder = ""
max_result_length = 10
snippet_length = 30
highlight_tag = "em"
absolute_url = false

[params.related]
enable = true
count = 5

[params.search.fuse]
is_case_sensitive = false
min_match_char_length = 2
find_all_matches = false
location = 0
threshold = 0.3
distance = 100
ignore_location = false
use_extended_search = false
ignore_field_norm = false

[params.social]
GitHub = "Heng-Mei"
RSS = false

[params.recently_updated]
archives = false
section = false
list = false
days = 30
max_count = 10

[menu]

[[menu.main]]
identifier = "github"
name = " "
url = "https://github.com/Heng-Mei"
weight = 1

[[menu.main]]
name = "共思录"
url = "/dialogues/"
weight = 9

[[menu.main]]
name = "随想"
url = "/posts/"
weight = 10

[[menu.main]]
name = "算法"
url = "/algorithms/"
weight = 12

[[menu.main]]
name = "笔记"
url = "/notes/"
weight = 15

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 20

[[menu.main]]
name = "合集"
url = "/collections/"
weight = 21

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 22

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 25

[markup]
[markup.highlight]
codeFences = true
lineNos = false
lineNumbersInTable = true
noClasses = false

[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[params.math]
enable = true
type = "mathjax"
# MathJax server-side rendering (https://www.mathjax.org)
# MathJax config: https://docs.mathjax.org/en/latest/options/index.html
[params.math.mathjax]
cdn = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
[params.math.mathjax.packages]
"[+]" = ["physics", "xypic"]
# custom macros map
# syntax: <macro> = <definition>
[params.math.mathjax.macros]
# "bold" = ["{\\bf #1}", 1]   # usage: $\bold{math}$
[params.math.mathjax.loader]
load = ["ui/safe", "[tex]/physics", "[custom]/xypic.js"]
[params.math.mathjax.loader.paths]
custom = "https://fastly.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build"
[params.math.mathjax.options]
enable_menu = true
# HTML tags that won't be searched for math
skip_html_tags = [
  "script",
  "noscript",
  "style",
  "textarea",
  "pre",
  "code",
  "math",
  "select",
  "option",
  "mjx-container",
]
# class that marks tags not to search
ignore_html_class = "mathjax_ignore"
# HTML tags that can appear within math
[params.math.mathjax.options.include_html_tags]
# "#comment" = ""
# br = "\n"
# wbr = ""

[params.math.mathjax.tex]
tags = "all"
process_escapes = true
process_environments = true

[params.math.mathjax.tex.physics]
italicdiff = false
arrowdel = false

[params.post_link]
markdown = false
source = false
edit = false
report = false
editor = ""

# 目录配置
[params.toc]
auto = false
ordered = true

[params.heading.number]
enable = true

[params.heading.number.format]
h1 = "{title}"
h2 = "{h2} {title}"
h3 = "{h2}.{h3} {title}"
h4 = "{h2}.{h3}.{h4} {title}"
h5 = "{h2}.{h3}.{h4}.{h5} {title}"
h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"

[params.share]
enable = false

# 第三方库配置
[params.library]

[params.library.css]
# someCSS = "some.css"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"

[params.library.js]
# someJavascript = "some.js"
# 位于 "assets/"
# 或者
# someJavascript = "https://cdn.example.com/some.js"


[caches]
[caches.images]
dir = ":cacheDir/images"

[params.verification]
google = "BZknj698kPXN9fxHxb1vFvdc0d-luCM1UYEY0olmDZk"
bing = "5E7A7EA66C53643B33B56812868ABDDA"
